### ISSUE TITLE
放到自己项目没有生成patch文件

### ISSUE THREAD

**Issue by LiJunyang** [jasonross/Nuwa#10]
用你的demo成功了。
然后放到自己项目里面试了下，发现没生成patch文件，只生成了一个patch目录。命令行运行生成补丁的命令是成功的，但是就是没有文件出来。求解

**Comment by jasonross** [comment]
@LiJunyang  patch目录里有东西吗？看一下命令行输出有什么提示吗？

**Comment by hfbi360** [comment]
Desktop/nuwa/release/mapping.txt does not exist

**Comment by ladddd** [comment]
遇到了相同的问题 qihoo/debug 下生成了一个patch空目录， 并没有jar。
**_@**_PC:~/Project/Nuwa$ ./gradlew clean nuwaQihooDebugPatch -P NuwaDir=/home/***/Project/Nuwa/sample/build/outputs/nuwa
Parallel execution with configuration on demand is an incubating feature.
:clean
:nuwa:clean UP-TO-DATE
:sample:clean
:nuwa:compileLint
:nuwa:copyReleaseLint UP-TO-DATE
:nuwa:mergeReleaseProguardFiles UP-TO-DATE
:nuwa:preBuild UP-TO-DATE
:nuwa:preReleaseBuild UP-TO-DATE
:nuwa:checkReleaseManifest
:nuwa:prepareReleaseDependencies
:nuwa:compileReleaseAidl
:nuwa:compileReleaseRenderscript
:nuwa:generateReleaseBuildConfig
:nuwa:generateReleaseAssets UP-TO-DATE
:nuwa:mergeReleaseAssets
:nuwa:generateReleaseResValues UP-TO-DATE
:nuwa:generateReleaseResources
:nuwa:packageReleaseResources
:nuwa:processReleaseManifest
:nuwa:processReleaseResources
:nuwa:generateReleaseSources
:nuwa:processReleaseJavaRes UP-TO-DATE
:nuwa:compileReleaseJava
:sample:preBuild UP-TO-DATE
:sample:preQihooDebugBuild UP-TO-DATE
:sample:checkQihooDebugManifest
:sample:preQihooReleaseBuild UP-TO-DATE
:sample:preXiaomiDebugBuild UP-TO-DATE
:sample:preXiaomiReleaseBuild UP-TO-DATE
:sample:generateQihooDebugBuildConfig
:sample:generateQihooDebugAssets UP-TO-DATE
:sample:generateQihooDebugResValues UP-TO-DATE
:sample:processQihooDebugJavaRes UP-TO-DATE
:nuwa:packageReleaseJar
:nuwa:compileReleaseNdk UP-TO-DATE
:nuwa:packageReleaseJniLibs UP-TO-DATE
:nuwa:packageReleaseLocalJar UP-TO-DATE
:nuwa:packageReleaseRenderscript UP-TO-DATE
:nuwa:bundleRelease
:sample:prepareCnJiajixinNuwaNuwa100Library
:sample:prepareComAndroidSupportAppcompatV72221Library
:sample:prepareComAndroidSupportDesign2221Library
:sample:prepareComAndroidSupportSupportV42221Library
:sample:prepareQihooDebugDependencies
:sample:compileQihooDebugAidl
:sample:compileQihooDebugRenderscript
:sample:mergeQihooDebugAssets
:sample:generateQihooDebugResources
:sample:mergeQihooDebugResources
:sample:processQihooDebugManifest
:sample:processQihooDebugResources
:sample:generateQihooDebugSources
:sample:compileQihooDebugJava
:sample:proguardQihooDebug
Warning: can't write resource [.readme](Duplicate zip entry [classes.jar:.readme])
:sample:nuwaJarBeforeDexQihooDebug
:sample:nuwaQihooDebugPatch

BUILD SUCCESSFUL

Total time: 3.347 secs
