### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by yexin4133** [jasonross/Nuwa#13]
15:01:56.333 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
15:01:56.333 [ERROR] [org.gradle.BuildExceptionReporter]    at cn.jiajixin.nuwa.NuwaPlugin$_apply_closure1_closure2_closure9_closure12.doCall(NuwaPlugin.groovy:127)
15:01:56.333 [ERROR] [org.gradle.BuildExceptionReporter]    at cn.jiajixin.nuwa.NuwaPlugin$_apply_closure1_closure2_closure9.doCall(NuwaPlugin.groovy:121)
15:01:56.333 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:558)
15:01:56.333 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:539)
15:01:56.334 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
15:01:56.334 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
15:01:56.334 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
15:01:56.334 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
15:01:56.334 [ERROR] [org.gradle.BuildExceptionReporter]    ... 57 more
15:01:56.334 [ERROR] [org.gradle.BuildExceptionReporter]

**Comment by Qiu800820** [comment]
@jasonross 怪我， 没编译就Pull了

**Comment by yexin4133** [comment]
@Qiu800820 这个啥时候能解决?

**Comment by Qiu800820** [comment]
@yexin4133 等作者看到， 我这没环境  存网页修改

**Comment by Qiu800820** [comment]
@yexin4133 我看你的错误是数组越界， 我编译没问题...   你是用simple测试的还是啥

**Comment by jasonross** [comment]
@yexin4133 你的什么环境说一下

**Comment by yexin4133** [comment]
@jasonross 

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

```
defaultConfig {
    applicationId "ye.com.nuwa"
    minSdkVersion 9
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:design:23.0.1'
    compile 'cn.jiajixin.nuwa:nuwa:1.0.0'
}

apply plugin: "cn.jiajixin.nuwa"

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        classpath 'cn.jiajixin.nuwa:gradle:1.2.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by yexin4133** [comment]
@Qiu800820  用的是sdk

**Comment by jasonross** [comment]
@yexin4133  项目是不是比较简单，可以clone给我吗？

**Comment by yexin4133** [comment]
@jasonross 给个邮箱我发给你吧。

**Comment by jasonross** [comment]
@yexin4133   jiajixin@gmail.com
