### ISSUE TITLE
dx --dex问题

### ISSUE THREAD

**Issue by htwahzs** [jasonross/Nuwa#18]
为什么我用dx --dex --output=patch.apk patch生成的apk文件中没有dex文件呢。
不会生成classes.dex

**Comment by htwahzs** [comment]
@jasonross

**Comment by jasonross** [comment]
@htwahzs  patch文件夹中有文件吗？

**Comment by jasonross** [comment]
@htwahzs  patch文件夹中有文件吗？

**Comment by jasonross** [comment]
@htwahzs  patch文件夹中有文件吗？

**Comment by htwahzs** [comment]
有  用javac ***.java 生成的class文件

**Comment by htwahzs** [comment]
我在patch中直接放.java，编译出来的是不带classes.dex的
如果放javac 编译出来的.class文件，会报错
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes

**Comment by jasonross** [comment]
@htwahzs dex命令有报错吗

**Comment by htwahzs** [comment]
是不是环境配置哪里有问题？

**Comment by jasonross** [comment]
@htwahzs 为啥不用我提供的gradle插件

**Comment by htwahzs** [comment]
gradle会报错啊。。之前说的个。
而且想搞清楚怎么回事，是不是javac编译成class文件需要一些配置什么的。

**Comment by htwahzs** [comment]
@jasonross 我用这个dx是为了生成补丁，gradle插件能生成补丁吗？

**Comment by jasonross** [comment]
@htwahzs 看一下README，再看一下源码就懂了啊
