### ISSUE TITLE
不支持新版本的gradle？

### ISSUE THREAD

**Issue by appdev** [jasonross/Nuwa#22]
我将gradle版本修改为1.5后：classpath 'com.android.tools.build:gradle:1.5.0'
项目会报这个错 Error:Cannot get property 'taskDependencies' on null object
导致项目初始化失败！

**Comment by jasonross** [comment]
@huclengyue  是的

**Comment by appdev** [comment]
还有一个问题，我运行./gradlew clean nuwaQihooDebugPatch -P NuwaDir=/Users/jason/Documents/nuwa 结果build失败提示：
FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':sample'.
  >  does not exist
  Google了一下参考stackoverflow的回答，设置了Android SDK的变量还是不行最后做了一个软连接到AS目录下也是报这个错= = ！

**Comment by appdev** [comment]
好了，是我第二步没看清除。我这渣英语- -！

**Comment by e-snail** [comment]
然后呢？貌似还是没有解决
@jasonross

**Comment by wogenhaosini** [comment]
Instant Run 也没法用 升级gradle即报错。
