### ISSUE TITLE
生成补丁failed，求解决

### ISSUE THREAD

**Issue by TigerSkinZhang** [jasonross/Nuwa#37]
![qq 20160106164621](https://cloud.githubusercontent.com/assets/5920424/12138685/98b32116-b495-11e5-94b8-d510914b83ae.png)

**Comment by xyggun** [comment]
我也碰到了，你把你的ANDROID_HOME 的环境变量配置好就行了

**Comment by TigerSkinZhang** [comment]
ok,thanks! 我也解决了。
 参照这个：http://my.oschina.net/u/1266171/blog/360299
关键是设置以下三个环境变量
ANDROID_HOME =  D:\Android\adt-bundle3\adt-bundle-windows-x86-20131030\sdk

ANDROID_PLATFORM_TOOLS = D:\Android\adt-bundle3\adt-bundle-windows-x86-20131030\sdk\platform-tools

 ANDROID_TOOLS = D:\Android\adt-bundle3\adt-bundle-windows-x86-20131030\sdk\tools
