### ISSUE TITLE
 java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation

### ISSUE THREAD

**Issue by lvzhaohuaGG** [jasonross/Nuwa#39]
用到修改的类时一直报 java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation 这个错误

**Comment by YuFong** [comment]
throws掉啊。。

**Comment by YuFong** [comment]
@lvzhaohuaGG throws掉就好

**Comment by siyehua** [comment]
@YuFong 怎么throws掉,我使用try catch还是不行

**Comment by YuFong** [comment]
@siyehua 直接在类（方法）后面throws异常，不用try catch（估计你也是包错了地方才会不行）
