### ISSUE TITLE
没找到bugfix分支.另外sample生成的patch.jar在哪

### ISSUE THREAD

**Issue by Eklett** [jasonross/Nuwa#4]
rt

**Comment by jasonross** [comment]
抱歉，bugfix分支刚刚添加。
sample/build/outputs/nuwa/qihoo/debug/patch.jar

**Comment by lincleejun** [comment]
![image](https://cloud.githubusercontent.com/assets/994251/11110107/fd04f0e2-8932-11e5-8dd3-9a98ba3c75f9.png)

生成的结果是空的。

**Comment by Eklett** [comment]
我这边是可以的.

**Comment by jasonross** [comment]
@Eklett  一加的可以吗

**Comment by jasonross** [comment]
@lincleejun  patch文件夹是空的吧，有按照run the sample步骤来操作吗？

**Comment by Eklett** [comment]
可以的 @jasonross

**Comment by jasonross** [comment]
@Eklett  very cool，3q

**Comment by jasonross** [comment]
@lincleejun  你搞定了吗？

**Comment by JakeWoki** [comment]
没看到patch.jar在哪，也执行不了./gradlew clean nuwaQihooDebugPatch -P NuwaDir=/Users/jason/Documents/nuwa，能说详细点吗

**Comment by Eklett** [comment]
@JakeWoki 先跑一次sample ,然后把sample/build/outputs/nuwa这个文件夹复制到{your dir},再切换分支,执行./gradlew clean nuwaQihooDebugPatch -P NuwaDir={your dir}/nuwa....  run the sample步骤说的很清楚了啊,

**Comment by JakeWoki** [comment]
可是没有jar生成，只在sample\build\outputs\nuwa\qihoo\debug\patch\cn\jiajixin\nuwasample\a文件夹看到一个a.class文件

**Comment by jasonross** [comment]
@JakeWoki 执行不了那行命令吗？

**Comment by JakeWoki** [comment]
可以执行，不过生成的是各种xxx.class文件

**Comment by jasonross** [comment]
@JakeWoki 先生成各种class文件，然后会把这些文件打成patch.jar，如果有class文件，但没生成patch.jar，估计是有报错信息，在命令行中可以看到。

**Comment by xujianhuaap** [comment]
Executing task ':app:nuwaDebugPatch' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.

**Comment by xujianhuaap** [comment]
@jasonross  Executing task ':app:nuwaDebugPatch' (up-to-date check took 0.001 secs) due to:
Task has not declared any outputs. 这个造成jar 文件出不来
