### ISSUE TITLE
gradlew clean 错误

### ISSUE THREAD

**Issue by jayronlou** [jasonross/Nuwa#5]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':sample'.
> Could not find property 'property' on project ':sample'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by jasonross** [comment]
@jayronlou  ./gradlew clean --stacktrace --debug > log.txt

then copy log.txt to me

**Comment by jasonross** [comment]
@jayronlou  you must add -P NuwaDir, but the file does not exist.
There is a little bug ,and I will fix it right now.

**Comment by jasonross** [comment]
this bug has been fixed, please pull the newest code and try again
