### ISSUE TITLE
 classpath 'cn.jiajixin.nuwa:gradle:1.2.1'

### ISSUE THREAD

**Issue by 23code** [jasonross/Nuwa#7]
classpath 'cn.jiajixin.nuwa:gradle:1.2.1'  这个依赖是怎么实现的，有没有代码看看呀，jcenter上搜索不出来额。

**Comment by jasonross** [comment]
@23code  现在是1.2.2了，这个是jcenter地址：http://jcenter.bintray.com/cn/jiajixin/nuwa/gradle/1.2.2/。

代码在[NuwaGradle](https://github.com/jasonross/NuwaGradle)，在我的开源项目里，README里也有链接。
